// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Fields we track in change history.
 */
export type HistoryField = "price" | "mls_number" | "listed_date" | "source_status" | { "other": string };
