// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Execution state of the background agent review task.
 */
export type AgentReviewState = "Running" | "Succeeded" | "Failed";
