// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Fields we track in change history.
 */
export type HistoryField = "Price" | "MlsNumber" | "ListedDate" | "SourceStatus";
