// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A record of a field value change on a listing (e.g. price went from X to Y).
 */
export type HistoryEntry = { id: bigint, listing_id: bigint, field_name: string, old_value: string | null, new_value: string | null, changed_at: string, };
