// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single image entry associated with a property listing.
 * Can be a local cached file or a remote URL.
 */
export type ImageEntry = { id: bigint, url: string, created_at: string, };
