// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The user-facing status of a listing.
 * Stored in SQLite as its display name ("Interested", "Buyable", "Pass").
 */
export type ListingStatus = "Pending" | "Interested" | "Buyable" | "Pass";
