// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single open house event for a listing.
 */
export type OpenHouse = { id: bigint, listing_id: bigint, start_time: string, end_time: string | null, visited: boolean, created_at: string, };
