// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageEntry } from "./ImageEntry";
import type { ListingStatus } from "./ListingStatus";
import type { OpenHouse } from "./OpenHouse";
import type { SourceStatus } from "./SourceStatus";

/**
 * A real estate property with all parsed and user-tracked fields.
 * Images are populated separately from the images_cache table.
 *
 * Field annotations:
 *   editable            — user can update via PATCH /api/listings/:id/details
 *   parsed; editable    — initially filled by the parser; user can override
 *   parsed; display only — filled by the parser; no UI edit control
 *   derived; read-only  — recomputed server-side on every save
 *   system              — managed entirely by the server / DB
 */
export type Property = { id: bigint, search_profile_id: bigint | null, title: string, description: string, price: bigint | null, price_currency: string | null, street_address: string | null, city: string | null, region: string | null, postal_code: string | null, country: string | null, lat: number | null, lon: number | null, property_type: string | null, bedrooms: bigint | null, bathrooms: bigint | null, sqft: bigint | null, land_sqft: bigint | null, year_built: bigint | null, parking_total: bigint | null, parking_garage: bigint | null, parking_carport: bigint | null, parking_pad: bigint | null, radiant_floor_heating: boolean | null, ac: boolean | null, laundry_in_unit: boolean | null, skytrain_station: string | null, skytrain_walk_min: bigint | null, 
/**
 * User's intended offer price — drives all mortgage calculations.
 * When null the application falls back to `price` for calculations.
 */
offer_price: bigint | null, property_tax: bigint | null, hoa_monthly: bigint | null, down_payment_pct: number | null, mortgage_interest_rate: number | null, amortization_years: bigint | null, mortgage_monthly: bigint | null, monthly_total: bigint | null, monthly_cost: bigint | null, has_rental_suite: boolean | null, rental_income: bigint | null, school_elementary: string | null, school_elementary_rating: number | null, school_middle: string | null, school_middle_rating: number | null, school_secondary: string | null, school_secondary_rating: number | null, redfin_url: string | null, realtor_url: string | null, rew_url: string | null, zillow_url: string | null, mls_number: string | null, listed_date: string | null, source_status: SourceStatus | null, status: ListingStatus, notes: string | null, agent_comment: string | null, 
/**
 * Populated from images_cache, not stored directly in listings.
 */
images: Array<ImageEntry>, 
/**
 * Populated from open_houses table, not stored directly in listings.
 */
open_houses: Array<OpenHouse>, created_at: string, updated_at: string | null, };
