// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A saved search profile / project that groups related property listings.
 */
export type SearchProfile = { id: bigint, title: string, description: string, position: bigint, created_at: string, updated_at: string | null, 
/**
 * Number of listings belonging to this search profile (populated by queries).
 */
listing_count: bigint, };
