// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The market status of a listing as reported by the source website (Redfin, REW, etc.).
 *
 * This is distinct from [`ListingStatus`], which tracks *our own* internal workflow state
 * (what the user or agent is doing with the listing). `SourceStatus` reflects the listing's
 * **market reality** — whether it is still for sale, under contract, or gone.
 *
 * `source_status` on a property is `None` when the listing is actively for sale (the normal
 * state). A non-`None` value means something has changed on the market side and the listing
 * is no longer straightforwardly available. This is set by the parser on each fetch and
 * overwritten on refresh; it is never set by the user.
 *
 * # Relationship to `ListingStatus`
 *
 * | `ListingStatus`     | Who sets it  | What it means                                    |
 * |---------------------|--------------|--------------------------------------------------|
 * | `AgentPending`      | System       | Just added; the agent has not reviewed it yet    |
 * | `HumanReview`      | Agent        | Approved by agent; awaiting human decision       |
 * | `AgentSkip`         | Agent        | Agent decided no profile matches                 |
 * | `Interested` etc.   | User         | User's personal tracking state                   |
 *
 * | `SourceStatus`      | Who sets it  | What it means                                    |
 * |---------------------|--------------|--------------------------------------------------|
 * | `None`              | Parser       | Active — listing is currently for sale           |
 * | `Pending`           | Parser       | Sale pending — offer accepted, not yet closed    |
 * | `OffMarket`         | Parser       | No longer listed — withdrawn, expired, or sold   |
 * | `Sold`              | Parser       | Confirmed sold / closed                          |
 * | `Unknown(s)`        | Parser       | Any other status string from the source site     |
 * Serializes and deserializes as a plain string (e.g. `"Pending"`, `"Off Market"`).
 */
export type SourceStatus = string;
